apply black -l 75 to all code
bluesky/hklpy pull request #105
Opened 2021-01-17 18:03 UTC by prjemian

All code commits must pass flake8 (already a CI requirement).  Apply `black -l 75` code styling to all python files (except vendor code such as versioneer files).

2021-01-17 18:05 UTC, prjemian commented
Also apply some protections against the aggressive styling of `black`, using `# fmt: off` & `#fmt: on` boundaries.  Sometimes, the source code is written so that a human might read it.

2021-01-17 18:16 UTC, prjemian commented
@mrakitin : ready for review

2021-01-19 22:42 UTC, mrakitin reviewed
I wonder if we should rather keep a more-restricted line length of 115 symbols? That's done, e.g. in https://github.com/bluesky/bluesky-queueserver/blob/main/pyproject.toml, and we run the [linter action](https://github.com/bluesky/bluesky-queueserver/blob/main/.github/workflows/black.yml) there to enforce it (it will use the same `pyproject.toml` configuration).

I am not against the 75-symbol limitation, just would make sense to keep these number in sync between `flake8` and `black`. So, in addition to the 75- and 115-symbol max line length, we have two more options:
- 79 ([PEP8 recommendation](https://www.python.org/dev/peps/pep-0008/#maximum-line-length))
- 120 ([default in Pycharm](https://stackoverflow.com/a/17319775))

What should we pick?

2021-01-19 22:42 UTC, mrakitin commented on .flake8
>  max-line-length = 115
The flake8 boundary is 115 symbols. Would it make sense to coordinate it with `black`'s configuration?

2021-01-20 00:25 UTC, prjemian commented on .flake8
>  max-line-length = 115
75 is my arbitrary choice based on screen readbility.  If we use 115 in other bluesky packages, then let's go with the flow.

2021-01-20 00:26 UTC, prjemian commented on .flake8
>  max-line-length = 115
read*a*bility

2021-01-20 16:27 UTC, prjemian commented
@mrakitin The Github Actions workflow for `black` applies the default line length, not `-l 115`.  I suggest we go with that.

```
(bluesky_2021_1) prjemian@poof ~/.../Bluesky/hklpy $ black --help
Usage: black [OPTIONS] [SRC]...

  The uncompromising code formatter.

Options:
  -c, --code TEXT                 Format the code passed in as a string.
  -l, --line-length INTEGER       How many characters per line to allow.
                                  [default: 88]
...
```

2021-01-20 16:41 UTC, prjemian commented
We can keep the 115 line length: see https://black.readthedocs.io/en/stable/pyproject_toml.html

2021-01-20 16:47 UTC, prjemian commented
The 1black .` test passes locally but continues to fail on GH Actions.  Likely to remove that action until we understand it better and can control it.

2021-01-20 16:49 UTC, prjemian commented
Example: https://github.com/bluesky/hklpy/pull/105/checks?check_run_id=1736316333#step:5:358

Will disable the `black.yml` workflow for now.  Can still apply the test locally but enforcement via GH Actions is problematic.

2021-01-20 16:53 UTC, prjemian commented
@mrakitin Ready for review

2021-01-20 17:41 UTC, mrakitin commented
> @mrakitin The Github Actions workflow for `black` applies the default line length, not `-l 115`. I suggest we go with that.
> 
> ```
> (bluesky_2021_1) prjemian@poof ~/.../Bluesky/hklpy $ black --help
> Usage: black [OPTIONS] [SRC]...
> 
>   The uncompromising code formatter.
> 
> Options:
>   -c, --code TEXT                 Format the code passed in as a string.
>   -l, --line-length INTEGER       How many characters per line to allow.
>                                   [default: 88]
> ...
> ```

As mentioned above, it uses such a file for the configuration: https://github.com/bluesky/bluesky-queueserver/blob/main/pyproject.toml. With that configuration, the linter action should work fine.

And, now we have another, `black`'s default of 88 symbols.

2021-01-20 17:43 UTC, mrakitin commented
> We can keep the 115 line length: see https://black.readthedocs.io/en/stable/pyproject_toml.html

Oops, did not read this comment. I see you added it in the following commits.

2021-01-20 18:17 UTC, mrakitin commented
When I run it locally, I still see those 7 files changed:
```bash
$ black .
reformatted /Users/mrakitin/src/mrakitin/DAMA/hklpy/docs/source/conf.py
reformatted /Users/mrakitin/src/mrakitin/DAMA/hklpy/hkl/diffract.py
reformatted /Users/mrakitin/src/mrakitin/DAMA/hklpy/hkl/engine.py
reformatted /Users/mrakitin/src/mrakitin/DAMA/hklpy/hkl/tests/test_diffract.py
reformatted /Users/mrakitin/src/mrakitin/DAMA/hklpy/hkl/util.py
reformatted /Users/mrakitin/src/mrakitin/DAMA/hklpy/hkl/calc.py
reformatted /Users/mrakitin/src/mrakitin/DAMA/hklpy/hkl/tests/test_tardis.py
All done! ✨ 🍰 ✨
7 files reformatted, 10 files left unchanged.
$ black --version
black, version 20.8b1
```

What's different on your side, @prjemian?

2021-01-20 18:29 UTC, prjemian commented
```
(bluesky_2021_1) prjemian@poof ~/Documents/raw $ black --version
black, version 19.10b0
(bluesky_2021_1) prjemian@poof ~/Documents/raw $ python --version
Python 3.8.2
```

I'll try upgrading black

2021-01-20 18:38 UTC, prjemian commented
My version of `black` is conda-installed.  No updates proposed for `black` with `conda update black -c defaults -c conda-forge -c nsls2forge` so updated via pip:
```
(bluesky_2021_1) prjemian@poof ~/Documents/raw $ pip install -U black
Requirement already satisfied: black in /home/prjemian/Apps/anaconda/envs/bluesky_2021_1/lib/python3.8/site-packages (19.10b0)
Collecting black
  Downloading black-20.8b1.tar.gz (1.1 MB)
     |████████████████████████████████| 1.1 MB 793 kB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: typed-ast>=1.4.0 in /home/prjemian/Apps/anaconda/envs/bluesky_2021_1/lib/python3.8/site-packages (from black) (1.4.2)
Requirement already satisfied: toml>=0.10.1 in /home/prjemian/Apps/anaconda/envs/bluesky_2021_1/lib/python3.8/site-packages (from black) (0.10.1)
Requirement already satisfied: pathspec<1,>=0.6 in /home/prjemian/Apps/anaconda/envs/bluesky_2021_1/lib/python3.8/site-packages (from black) (0.7.0)
Requirement already satisfied: appdirs in /home/prjemian/Apps/anaconda/envs/bluesky_2021_1/lib/python3.8/site-packages (from black) (1.4.4)
Requirement already satisfied: typing-extensions>=3.7.4 in /home/prjemian/Apps/anaconda/envs/bluesky_2021_1/lib/python3.8/site-packages (from black) (3.7.4.3)
Requirement already satisfied: regex>=2020.1.8 in /home/prjemian/Apps/anaconda/envs/bluesky_2021_1/lib/python3.8/site-packages (from black) (2020.11.13)
Requirement already satisfied: click>=7.1.2 in /home/prjemian/Apps/anaconda/envs/bluesky_2021_1/lib/python3.8/site-packages (from black) (7.1.2)
Requirement already satisfied: mypy-extensions>=0.4.3 in /home/prjemian/Apps/anaconda/envs/bluesky_2021_1/lib/python3.8/site-packages (from black) (0.4.3)
Building wheels for collected packages: black
  Building wheel for black (PEP 517) ... done
  Created wheel for black: filename=black-20.8b1-py3-none-any.whl size=124184 sha256=8e790cca456afa2ea0def41b82e66f5ff9e069b4e58f3a96a5c99686f66a9609
  Stored in directory: /home/prjemian/.cache/pip/wheels/95/a4/59/10cd5378d52f92cdb45025f040e4686e10ae5217961c25fd66
```

```
(bluesky_2021_1) prjemian@poof ~/Documents/raw $ black --version
black, version 20.8b1
(bluesky_2021_1) prjemian@poof ~/Documents/raw $ cd ../projects/Bluesky/hklpy/
(bluesky_2021_1) prjemian@poof ~/.../Bluesky/hklpy $ make black
black .
reformatted /home/prjemian/Documents/projects/Bluesky/hklpy/docs/source/conf.py
reformatted /home/prjemian/Documents/projects/Bluesky/hklpy/hkl/diffract.py
reformatted /home/prjemian/Documents/projects/Bluesky/hklpy/hkl/engine.py
reformatted /home/prjemian/Documents/projects/Bluesky/hklpy/hkl/tests/test_diffract.py
reformatted /home/prjemian/Documents/projects/Bluesky/hklpy/hkl/util.py
reformatted /home/prjemian/Documents/projects/Bluesky/hklpy/hkl/calc.py
reformatted /home/prjemian/Documents/projects/Bluesky/hklpy/hkl/tests/test_tardis.py
All done! ✨ 🍰 ✨
7 files reformatted, 10 files left unchanged.
```

Matches your numbers above now.  Yikes such dependencies!  Seems `black` is not sufficiently stable for us to use it in CI workflows.

2021-01-20 19:56 UTC, mrakitin commented
Yeah, that's surprising the close versions produce such different results.

As the fixes have been implemented, I believe we can re-enable the GitHub Actions config for `black` now. Let's see if it fails or succeeds.

2021-01-20 20:57 UTC, prjemian commented
@mrakitin You were right!  Success now.

2021-01-21 05:13 UTC, mrakitin requested changes
`black.yml` was completely removed in the last commit. I believe you intended to move it instead.

2021-01-21 15:02 UTC, merged