explain why the angles do not match
bluesky/hklpy pull request #84
Opened 2020-12-26 21:51 UTC by prjemian

FIX #66

@ambarb Agree that this explanation is satisfactory? Paraphrasing:

> ... the UB matrix can't just be copied [from SPEC to hklpy] and re-used. Need to compute [the UB matrix] from the supplied reflection angles (which is why the orientation reflection data must also be written into the run, per #50).

2021-01-04 16:48 UTC, mrakitin requested changes
It seems there is an issue with the notebook (see the syntax error in https://nbviewer.jupyter.org/github/bluesky/hklpy/blob/602638df90dd729cd50fcaa7a2af8d020474dc41/examples/tst_e4cv_fourc.ipynb#Setup-the-UB-orientation-matrix-using-hklpy). Needs to be fixed before merging.

2021-01-04 16:48 UTC, mrakitin commented on examples/tst_e4cv_fourc.ipynb
> +      "\u001b[0;36m  File \u001b[0;32m\"<ipython-input-11-3719be6e20be>\"\u001b[0;36m, line \u001b[0;32m18\u001b[0m\n\u001b[0;31m    tbl = pyRestTable.Table()compute\u001b[0m\n\u001b[0m
Why is there a syntax error?

2021-01-04 16:48 UTC, mrakitin commented on examples/tst_e4cv_fourc.ipynb
> +    "tbl = pyRestTable.Table()compute \n",
Should it be
```suggestion
    "tbl = pyRestTable.Table().compute \n",
```
?

2021-01-05 01:34 UTC, mrakitin approved these changes

2021-01-05 18:22 UTC, prjemian commented
@mrakitin Thanks!

2021-01-05 18:22 UTC, merged